"""generation counter per vault

Revision ID: 5321c3844a71
Revises: de99cd4f8935
Create Date: 2026-08-29 09:35:26.297679
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5321c3844a71'
down_revision: Union[str, None] = 'de99cd4f8935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault', schema=None) as batch_op:
        # server_default matters: without it the column cannot be added to a
        # table that already holds vaults. Dropped again right away so new rows
        # take their value from the model instead of from the schema.
        batch_op.add_column(
            sa.Column('next_generation', sa.Integer(), nullable=False, server_default='1')
        )
    with op.batch_alter_table('vault', schema=None) as batch_op:
        batch_op.alter_column('next_generation', server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault', schema=None) as batch_op:
        batch_op.drop_column('next_generation')

    # ### end Alembic commands ###
