"""sessions know their auth strength

Revision ID: 630824d9ded0
Revises: 8b50a162c06d
Create Date: 2026-08-29 10:51:50.968138
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '630824d9ded0'
down_revision: Union[str, None] = '8b50a162c06d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        # server_default so the column can be added while sessions exist. Old
        # sessions land on False - correct: nobody can vouch for how they came
        # to be, so they cannot add passkeys until their owner signs in afresh.
        batch_op.add_column(
            sa.Column('strong_auth', sa.Boolean(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('strong_auth')

    # ### end Alembic commands ###
