"""passkey challenges and login throttling

Revision ID: de99cd4f8935
Revises: 7799a247858c
Create Date: 2026-08-29 08:14:18.423467
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'de99cd4f8935'
down_revision: Union[str, None] = '7799a247858c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webauthn_challenge',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('challenge', sa.LargeBinary(), nullable=False),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_attempts')

    op.drop_table('webauthn_challenge')
    # ### end Alembic commands ###
